services:
  app:
    build:
      context: .
      args:
        BUILD_NUMBER: "1.0.0"
        GIT_REF: "a1b2c3"
        GIT_BRANCH: main
    networks:
      - tcom
    ports:
      - "3000:3000"
    environment:
      - PRODUCT_ID=UNASSIGNED
      - REDIS_ENABLED=false
      - REDIS_HOST=localhost
      - SESSION_SECRET=somesecretvalue
      - INGRESS_URL=http://localhost:3000
      - NO_HTTPS=true
      - POC_PASSWORD=supersecure
      - VALID_OTP=123456
      - POP_LOGIN_OTP=123456
      - POP_PASSWORD=supersecure

networks:
  tcom:
